questions =  [
    {"id": 0, "question": "Nationalism is dangerous, but there's nothing wrong with patriotism.", "effects": {"right": 1}},
    {"id": 1, "question": "We should strive for a world where no one can tell anyone else what to do.", "effects": {"right": 1}},
    {"id": 2, "question": "The debate over gender pronouns is just a distraction the powerful use to divide us against each other.", "effects": {"right": 1}},
    {"id": 3, "question": "Society must protect democratic minorities from the tyranny of the majority.", "effects": {"right": 1}},
    {"id": 4, "question": "Free speech is best protected with an absolute legal right.", "effects": {"right": 1}},
    {"id": 5, "question": "People with office jobs have more power than blue collar workers.", "effects": {"right": 1}},
    {"id": 6, "question": "Stalin was just as bad as Hitler.", "effects": {"right": 1}},
    {"id": 7, "question": "In war sometimes you have to fire the first shot.", "effects": {"right": 1}},
    {"id": 8, "question": "There was a time in the past when the world was better.", "effects": {"right": 1}},
    {"id": 9, "question": "The left and the right need to set aside their differences to make progress.", "effects": {"auth": 1}},
    {"id": 10, "question": "Groupthink has become a serious problem in our society.", "effects": {"auth": 1}},
    {"id": 11, "question": "People would revolt if they knew the truth.", "effects": {"auth": 1}},
    {"id": 12, "question": "It's best to assume that the mainstream media is lying.", "effects": {"auth": 1}},
    {"id": 13, "question": "We need to become just as good at psychological manipulation as our enemies.", "effects": {"auth": 1}},
    {"id": 14, "question": "Labelling things 'conspiracy theories' just protects the powerful.", "effects": {"auth": -1}},
    {"id": 15, "question": "Too many people are caught in political binaries.", "effects": {"auth": 1}},
    {"id": 16, "question": "I can predict election outcomes better than most people.", "effects": {"auth": 1}},
    {"id": 17, "question": "Most people don't question their beliefs.", "effects": {"auth": 1}},
    {"id": 18, "question": "My politics aren't really left or right.", "effects": {"auth": 1}},
    {"id": 19, "question": "I'm more right-wing than left-wing.", "effects": {"right": 1}},
];
